server:
  port: 8088

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/**
          filters:
            - E2ETrustTokenFilter
  redis:
    host: localhost
    port: 6379
    password:

e2etrust:
  filter:
    e2e-token-header: X-E2E-Trust-Token

security:
  authenticationEntryPoint: /auth/logon
  authorize:
    permitAll:
      - /favicon.ico
      - /auth/logon
      - /auth/logon-form
      - /auth/logon-failed
    hasAnyAuthority:
      - /others/**, ADMIN